geneAUC <- readRDS("gene_auc.rds")
geneROCPlot <- readRDS("gene_rocPlot.rds")
coadOnlyAUC <- readRDS("coadOnly_gene_auc.rds")
coadOnlyROC <- readRDS("coadOnly_gene_rocPlot.rds")
cnvROCPlot <- readRDS("cnv_DMR.rds")
cnvAUC <- readRDS("cnv_auc.rds")
cnvIndROC <- readRDS("cnv_rocPlot.rds")
combAUC <- readRDS("cnv_comb_auc1.rds")
#glmAUC <- readRDS("glm_comb_auc.rds")

geneList <- unique(geneAUC$gene)
#cnvList <- sort(c(unique(sapply(strsplit(cnvAUC$chrLoc,":"),`[`,1)),"DMR-overlapped"))
cnvList <- sort(c(unique(sapply(strsplit(cnvAUC$chrLoc,":"),`[`,1))))
cnvDUList <- unique(sapply(strsplit(cnvAUC$chrLoc[grep(":",cnvAUC$chrLoc)],":"),`[`,1))
